### ISSUE TITLE
"opam install usbmux" fails

### ISSUE THREAD

**Issue by ghost** [onlinemediagroup/ocaml-usbmux#11]
-

**Comment by fxfactorial** [comment]
Thanks! I will fix this tomorrow

**Comment by cclamb** [comment]
Hey everybody, I can't get it installed either. Initial installation seems okay, but no gandalf. Then I install camlp4 as instructed by the "opam depext usbmux.1.3.2" command. Then I tried another install, and this was the result:

opam install usbmux                                                                                                                                          
The following actions will be performed:
  ∗  install usbmux 1.3.2

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[usbmux] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[ERROR] The compilation of usbmux failed at "ocaml setup.ml -build".
Processing  1/1: [usbmux: ocaml]
#=== ERROR while installing usbmux.1.3.2 ======================================#
# opam-version 1.2.2
# os           darwin
# command      ocaml setup.ml -build
# path         /Users/cclamb/.opam/system/build/usbmux.1.3.2
# compiler     system (4.04.0)
# exit-code    1
# env-file     /Users/cclamb/.opam/system/build/usbmux.1.3.2/usbmux-79166-c61e7b.env
# stdout-file  /Users/cclamb/.opam/system/build/usbmux.1.3.2/usbmux-79166-c61e7b.out
# stderr-file  /Users/cclamb/.opam/system/build/usbmux.1.3.2/usbmux-79166-c61e7b.err
### stdout ###
# ocamlfind ocamlopt unix.cmxa -I /Users/cclamb/.opam/system/lib/ocamlbuild /Users/cclamb/.opam/system/lib/ocamlbuild/ocamlbuildlib.cmxa -linkpkg myocamlbuild.ml /Users/cclamb/.opa$/system/lib/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
# /Users/cclamb/.opam/system/bin/ocamlfind ocamldep -package yojson -package threads -package ppx_deriving_yojson -package ppx_deriving -package plist -package lwt.unix -package lw$.preemptive -package lwt.ppx -package cohttp.lwt -package cohttp -modules src/lib/usbmux.mli > src/lib/usbmux.mli.depends
# /Users/cclamb/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -g -w +a-4-40..42-44-45-48 -thread -package yojson -package threads -package ppx_deriving_yojson -package $px_deriving -package plist -package lwt.unix -package lwt.preemptive -package lwt.ppx -package cohttp.lwt -package cohttp -I src/lib -o src/lib/usbmux.cmi src/lib/usbmux.mli
# /Users/cclamb/.opam/system/bin/ocamlfind ocamldep -package yojson -package threads -package ppx_deriving_yojson -package ppx_deriving -package plist -package lwt.unix -package lw$.preemptive -package lwt.ppx -package cohttp.lwt -package cohttp -modules src/lib/usbmux.ml > src/lib/usbmux.ml.depends
# /Users/cclamb/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -g -w +a-4-40..42-44-45-48 -thread -package yojson -package threads -package ppx_deriving_yojson -package $px_deriving -package plist -package lwt.unix -package lwt.preemptive -package lwt.ppx -package cohttp.lwt -package cohttp -I src/lib -o src/lib/usbmux.cmo src/lib/usbmux.ml
# + /Users/cclamb/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -g -w +a-4-40..42-44-45-48 -thread -package yojson -package threads -package ppx_deriving_yojson -packag$ ppx_deriving -package plist -package lwt.unix -package lwt.preemptive -package lwt.ppx -package cohttp.lwt -package cohttp -I src/lib -o src/lib/usbmux.cmo src/lib/usbmux.ml
# File "src/lib/usbmux.ml", line 84, characters 11-15:
# Error: Unbound constructor Dict
# Command exited with code 2.
### stderr ###
# E: Failure("Command ''/Users/cclamb/.opam/system/bin/ocamlbuild' src/lib/usbmux.cma src/lib/usbmux.cmxa src/lib/usbmux.a src/lib/usbmux.cmxs src/app/main.native -use-ocamlfind -t$g debug' terminated with error code 10")



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
The following actions failed
  ∗  install usbmux 1.3.2
No changes have been performed

=-=- usbmux.1.3.2 troobleshooting -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
=> This package relies on external (system) dependencies that may be missing. `opam depext usbmux.1.3.2' may help you find the correct installation for your system.

thanks! Love gandalf!

**Comment by cclamb** [comment]
yikes! Sorry about the yelling there :-)

**Comment by fxfactorial** [comment]
Sorry, I'll try to fix today, my bad.

**Comment by cclamb** [comment]
Let me know when the fix is in and I'll give it another go and will let you
know how it goes.

**Comment by fxfactorial** [comment]
@cclamb 

please do:

```
$ opam update
$ opam install usbmux
```

Should be fixed now.

**Comment by windyzxcui** [comment]
Hi @fxfactorial , I cannot install usbmux either.
I got the following error code even run "opam update".
Please find the log for your investigation.

>opam install usbmux
The following actions will be performed:
  ∗  install usbmux 1.3.2

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[usbmux] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/.gitignore: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/.merlin: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/_build/_digests: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/_build/_log: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/_build/myocamlbuild: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/_build/myocamlbuild.cmi: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/_build/myocamlbuild.cmx: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/_build/myocamlbuild.ml: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/_build/myocamlbuild.o: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/_build/ocamlc.where: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/_build/src/lib/usbmux.annot: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/_build/src/lib/usbmux.cmi: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/_build/src/lib/usbmux.cmt: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/_build/src/lib/usbmux.cmti: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/_build/src/lib/usbmux.ml: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/_build/src/lib/usbmux.ml.depends: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/_build/src/lib/usbmux.mli: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/_build/src/lib/usbmux.mli.depends: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/_build/src/lib/usbmux.mllib: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/_build/src/lib: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/_build/src: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/_build: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/_oasis: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/_oasis_remove_.ml: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/_opam: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/_tags: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/configure: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/doc/api.odocl: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/doc/style.css: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/doc: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/install_man.sh: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/Makefile: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/myocamlbuild.ml: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/opam/descr: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/opam/findlib: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/opam/opam: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/opam: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/README.md: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/setup.data: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/setup.ml: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/src/app/gandalf_args.ml: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/src/app/main.ml: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/src/app: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/src/lib/META: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/src/lib/usbmux.ml: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/src/lib/usbmux.mldylib: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/src/lib/usbmux.mli: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/src/lib/usbmux.mllib: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/src/lib: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/src: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/usbmux-22567-c61e7b.env: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/usbmux-22567-c61e7b.err: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/usbmux-22567-c61e7b.info: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/usbmux-22567-c61e7b.out: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/usbmux-22567-d2d111.env: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/usbmux-22567-d2d111.err: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/usbmux-22567-d2d111.info: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/usbmux-22567-d2d111.out: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2/usbmux.install: Permission denied
rm: /Users/windycui/.opam/system/build/usbmux.1.3.2: Directory not empty

#=== ERROR while installing usbmux.1.3.2 ======================================#
# opam-version    1.2.2
# os              darwin
Cannot remove /Users/windycui/.opam/system/build/usbmux.1.3.2 (error 1).


=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
The following actions failed
  ∗  install usbmux 1.3.2
No changes have been performed

=-=- usbmux.1.3.2 troobleshooting -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
=> This package relies on external (system) dependencies that may be missing.
   `opam depext usbmux.1.3.2' may help you find the correct installation for
   your system.

**Comment by fxfactorial** [comment]
@windyzxcui Hi, this is unrelated to the original issue which was a legitimate build error. 

Your error is a UNIX permissions error, please make new issue for that.

**Comment by cclamb** [comment]
And sorry, I haven't had another MacBook to give this a try with yet. I
will be going on travel in July, and will have a new MacBook then, so I can
give it a shot at that point, or you can just push the change up whichever
works for you is fine with me. Thanks!
