### ISSUE TITLE
Disconnect and re-connect device

### ISSUE THREAD

**Issue by eni9889** [onlinemediagroup/ocaml-usbmux#2]
When I unplug a device and plug it back in the tunnel does not open and I have to restart gandalf. Is this the normal behavior?

**Comment by fxfactorial** [comment]
@eni9889 Hi, this is a known bug that I haven't been able to get to. Is it a big issue for you, I can fix it later this week.

**Comment by eni9889** [comment]
If you can that would be great. I use my personal device as my dev device and unplug it constantly. Also, amazing tool!!!

**Comment by fxfactorial** [comment]
@eni9889 I have a working implementation i think.

You'll need to do:

``` shell
$ git clone https://github.com/onlinemediagroup/ocaml-usbmux
$ cd ocaml-usbmux
$ opam pin add usbmux . -y
```

This will replace the one provided on opam upstream with this latest version from github. If you have any trouble check `opam switch` and do the `eval` that it tells you to do.

Let me know if that fixes it for you.

**Comment by eni9889** [comment]
Just tried it and everything seems to work although it seems if gandalf is started before a device is connected and later a device is connected gandalf has to be restarted

**Comment by fxfactorial** [comment]
Yes, the devices that you want to use should be plugged in when gandalf starts. This is something I can fix for the next iteration.

**Comment by fxfactorial** [comment]
@eni9889 I think this is now completely fixed. Please try again from source. Assuming that `opam` still has this pinned for you, you can do `git pull` and then `opam upgrade usbmux`, or just start from scratch. Will be releasing a new version on opam itself as well soon.
