### ISSUE TITLE
Only display post installation message on success

### ISSUE THREAD

**Issue by Chris00** [onlinemediagroup/ocaml-usbmux#7]
The post installation OPAM message should only be displayed on success as in https://github.com/the-lambda-church/merlin/blob/master/opam#L50  (you will probably want to make it a single string to not annotate all of them).

Also, if you want it to be automatically added up by `oasis2opam`, put the section `post-messages: [ ... ]` in an `_opam` file alongside `_oasis`.

**Comment by fxfactorial** [comment]
@Chris00 nice! I didn't know about { success }. I like the separate strings though cause it makes new lines. 

ah man, yet another file to make? a _opam?

**Comment by Chris00** [comment]
`_opam` is because, as `opam` is completely overwritten, you would have to reedit it each time you regenerate it.  `_opam` is _merged_ (in a simple way, mostly appended) in the generated `opam`.
